<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT60xp3C\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT60xp3C/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT60xp3C.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT60xp3C\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT60xp3C\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T60xp3C',
    'container.build_id' => 'd0c1f34d',
    'container.build_time' => 1588235682,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT60xp3C');
